services:
  postgres:
    container_name: postgres_container
    image: postgres:16-alpine3.21
    env_file: config.env
    volumes:
      - postgres:/data/postgres
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    networks:
      - postgres
    restart: unless-stopped


  application:
    build: .
    restart: always
    env_file: config.env
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: